# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140403200916) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "ove_2_card_versions", force: true do |t|
    t.integer  "card_id"
    t.integer  "version"
    t.integer  "project_id"
    t.integer  "number"
    t.string   "name"
    t.text     "description"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "created_by_user_id",                                             null: false
    t.integer  "modified_by_user_id",                                            null: false
    t.text     "comment"
    t.text     "system_generated_comment"
    t.string   "card_type_name",                                                 null: false
    t.boolean  "has_macros",                                     default: false, null: false
    t.string   "updater_id"
    t.integer  "cp_analyst_user_id"
    t.string   "cp_atc"
    t.string   "cp_automation"
    t.integer  "cp_related_card_card_id"
    t.string   "cp_caused_by_release"
    t.string   "cp_planning_estimate"
    t.string   "cp_committed_card"
    t.date     "cp_created_date"
    t.string   "cp_data_collection"
    t.integer  "cp_defect_card_id"
    t.string   "cp_defect_priority"
    t.string   "cp_defect_source"
    t.string   "cp_dev_capacity"
    t.string   "cp_planned_estimate"
    t.string   "cp_dev_pair"
    t.date     "cp_end_date"
    t.string   "cp_environment"
    t.integer  "cp_1_card_id"
    t.string   "cp_feature_estimate"
    t.string   "cp_feature_status"
    t.string   "cp_hangover_from"
    t.integer  "cp_initiative_tree___initiative_card_id"
    t.string   "cp_initiative_status"
    t.integer  "cp_planning_tree___iteration_card_id"
    t.integer  "cp_iteration_added_to_scope_card_id"
    t.integer  "cp_iteration_card_card_id"
    t.date     "cp_moved_to_complete___in_production_on"
    t.date     "cp_moved_to_new_on"
    t.integer  "cp_planning_tree___card_card_id"
    t.integer  "cp_planning_tree___defect_card_id"
    t.string   "cp_oracle_code"
    t.string   "cp_points_committed"
    t.integer  "cp_business_contact_user_id"
    t.integer  "cp_project_manager_user_id"
    t.string   "cp_project_type"
    t.string   "cp_qa_capacity"
    t.string   "cp_qa_commitment_estimate"
    t.string   "cp_release"
    t.string   "cp_reporter"
    t.string   "cp_resolution"
    t.string   "cp_defect_severity"
    t.date     "cp_start_date"
    t.string   "cp_status"
    t.string   "cp_stretch"
    t.string   "cp_team_1"
    t.integer  "cp_tester_user_id"
    t.date     "cp_moved_to_ready_for_deployment_on"
    t.date     "cp_moved_to_in_testing_on"
    t.string   "cp_time_to_fix"
    t.string   "cp_time_to_fix_iqd"
    t.string   "cp_total_commitment_estimate"
    t.string   "cp_total_commitment_estimate_completed"
    t.string   "cp_points_completed"
    t.string   "cp_total_feature_estimate_planned"
    t.string   "cp_total_cards"
    t.string   "cp_total_of_commitment_estimates"
    t.string   "cp_total_of_commitment_estimates_planned"
    t.string   "cp_ui_capacity"
    t.string   "cp_ui_commitment_estimate"
    t.string   "cp_ui_dev_contact"
    t.string   "cp_ux_contact"
    t.string   "cp_related_cards"
    t.integer  "cp_initiative_tree___ux_card_id"
    t.string   "cp_ux_priority"
    t.integer  "cp_ux_designer_user_id"
    t.integer  "cp_visual_designer_user_id"
    t.integer  "cp_content_manager_user_id"
    t.string   "cp_ux_status"
    t.string   "cp_2"
    t.string   "cp_3"
    t.string   "cp_4"
    t.string   "cp_brand"
    t.string   "cp_priority_score"
    t.string   "cp_dev_pts_estimate"
    t.string   "cp_business_approval"
    t.string   "cp_total_cards_1"
    t.string   "cp_total_of_commitment_estimates_1"
    t.string   "cp_dev_tasked_by"
    t.string   "cp_pulledin_dev_estimate"
    t.string   "cp_generic_managed_text_list"
    t.string   "cp_dev_sizing"
    t.string   "cp_quickstart"
    t.string   "cp_priority_to_deliver"
    t.string   "cp_hangover_notes"
    t.string   "cp_hangover_to"
    t.string   "cp_total_number_of_defects"
    t.string   "cp_total_number_of_test_cards"
    t.string   "cp_total_num_of_cards"
    t.integer  "cp_iteration_tree___internal_qa_defect_card_id"
    t.string   "cp_points_hangover"
    t.string   "cp_points_attempted"
    t.string   "cp_points_completed_1"
    t.string   "cp_iteration_number"
    t.string   "cp_integrated_testing"
    t.string   "cp_translations_needed"
    t.string   "cp_actual_dev_estimate"
    t.integer  "cp_qa_tasked_by_user_id"
    t.string   "cp_test_pair"
    t.string   "cp_automation_actual"
    t.string   "cp_automation_estimate"
    t.string   "cp_qa_actual"
    t.string   "cp_number_of_total_cards"
    t.integer  "cp_iqd_card_id"
    t.date     "cp_release_date"
    t.string   "cp_rollback"
    t.string   "cp_qa_integration"
    t.string   "cp_5"
    t.string   "cp_defect_introduced"
    t.string   "cp_dev_resources"
    t.string   "cp_qa_resources"
    t.string   "cp_total_deployment_resources"
    t.string   "cp_automated_testing_duration"
    t.string   "cp_deployment_duration"
    t.string   "cp_manual_testing_duration"
    t.string   "cp_pre_deployment_duration"
    t.string   "cp_code_deployment_duration"
    t.string   "cp_mobile_impact"
    t.integer  "cp_iteration_tree___test_card_id"
    t.boolean  "redcloth"
    t.string   "cp_dependent_cards_"
    t.string   "cp_committed_points_complete"
    t.string   "cp_1"
    t.string   "cp_content_"
    t.date     "cp_deployment_date"
    t.string   "cp_deployment"
    t.string   "cp_test"
    t.string   "cp_codebase_domain"
    t.string   "cp_dev_estimate_planning"
    t.string   "cp_iteration_tree___internal_qa_defect"
    t.string   "cp_total_dev_points_completed"
    t.string   "cp_total_number_of_cards"
    t.string   "cp_blocked"
    t.string   "cp_comments"
    t.string   "cp_dependent_on"
    t.string   "cp_dev_tasked_by_1"
    t.string   "cp_feature_file_tester"
    t.string   "cp_rollback_"
  end

  add_index "ove_2_card_versions", ["card_id"], name: "index_ove_2_card_versions_on_card_id", using: :btree
  add_index "ove_2_card_versions", ["number"], name: "index_ove_2_card_versions_on_number", using: :btree
  add_index "ove_2_card_versions", ["updated_at"], name: "index_ove_2_card_versions_on_updated_at", order: {"updated_at"=>:desc}, using: :btree
  add_index "ove_2_card_versions", ["version"], name: "index_ove_2_card_versions_on_version", using: :btree

  create_table "ove_2_cards", force: true do |t|
    t.integer  "project_id",                                                     null: false
    t.integer  "number",                                                         null: false
    t.string   "name",                                                           null: false
    t.text     "description"
    t.datetime "created_at",                                                     null: false
    t.datetime "updated_at",                                                     null: false
    t.integer  "version"
    t.integer  "created_by_user_id",                                             null: false
    t.integer  "modified_by_user_id",                                            null: false
    t.string   "card_type_name",                                                 null: false
    t.boolean  "has_macros",                                     default: false, null: false
    t.integer  "project_card_rank"
    t.integer  "caching_stamp",                                  default: 0,     null: false
    t.integer  "cp_analyst_user_id"
    t.string   "cp_atc"
    t.string   "cp_automation"
    t.integer  "cp_related_card_card_id"
    t.string   "cp_caused_by_release"
    t.string   "cp_planning_estimate"
    t.string   "cp_committed_card"
    t.date     "cp_created_date"
    t.string   "cp_data_collection"
    t.integer  "cp_defect_card_id"
    t.string   "cp_defect_priority"
    t.string   "cp_defect_source"
    t.string   "cp_dev_capacity"
    t.string   "cp_planned_estimate"
    t.string   "cp_dev_pair"
    t.date     "cp_end_date"
    t.string   "cp_environment"
    t.integer  "cp_1_card_id"
    t.string   "cp_feature_estimate"
    t.string   "cp_feature_status"
    t.string   "cp_hangover_from"
    t.integer  "cp_initiative_tree___initiative_card_id"
    t.string   "cp_initiative_status"
    t.integer  "cp_planning_tree___iteration_card_id"
    t.integer  "cp_iteration_added_to_scope_card_id"
    t.integer  "cp_iteration_card_card_id"
    t.date     "cp_moved_to_complete___in_production_on"
    t.date     "cp_moved_to_new_on"
    t.integer  "cp_planning_tree___card_card_id"
    t.integer  "cp_planning_tree___defect_card_id"
    t.string   "cp_oracle_code"
    t.string   "cp_points_committed"
    t.integer  "cp_business_contact_user_id"
    t.integer  "cp_project_manager_user_id"
    t.string   "cp_project_type"
    t.string   "cp_qa_capacity"
    t.string   "cp_qa_commitment_estimate"
    t.string   "cp_release"
    t.string   "cp_reporter"
    t.string   "cp_resolution"
    t.string   "cp_defect_severity"
    t.date     "cp_start_date"
    t.string   "cp_status"
    t.string   "cp_stretch"
    t.string   "cp_team_1"
    t.integer  "cp_tester_user_id"
    t.date     "cp_moved_to_ready_for_deployment_on"
    t.date     "cp_moved_to_in_testing_on"
    t.string   "cp_time_to_fix"
    t.string   "cp_time_to_fix_iqd"
    t.string   "cp_total_commitment_estimate"
    t.string   "cp_total_commitment_estimate_completed"
    t.string   "cp_points_completed"
    t.string   "cp_total_feature_estimate_planned"
    t.string   "cp_total_cards"
    t.string   "cp_total_of_commitment_estimates"
    t.string   "cp_total_of_commitment_estimates_planned"
    t.string   "cp_ui_capacity"
    t.string   "cp_ui_commitment_estimate"
    t.string   "cp_ui_dev_contact"
    t.string   "cp_ux_contact"
    t.string   "cp_related_cards"
    t.integer  "cp_initiative_tree___ux_card_id"
    t.string   "cp_ux_priority"
    t.integer  "cp_ux_designer_user_id"
    t.integer  "cp_visual_designer_user_id"
    t.integer  "cp_content_manager_user_id"
    t.string   "cp_ux_status"
    t.string   "cp_2"
    t.string   "cp_3"
    t.string   "cp_4"
    t.string   "cp_brand"
    t.string   "cp_priority_score"
    t.string   "cp_dev_pts_estimate"
    t.string   "cp_business_approval"
    t.string   "cp_total_cards_1"
    t.string   "cp_total_of_commitment_estimates_1"
    t.string   "cp_dev_tasked_by"
    t.string   "cp_pulledin_dev_estimate"
    t.string   "cp_generic_managed_text_list"
    t.string   "cp_dev_sizing"
    t.string   "cp_quickstart"
    t.string   "cp_priority_to_deliver"
    t.string   "cp_hangover_notes"
    t.string   "cp_hangover_to"
    t.string   "cp_total_number_of_defects"
    t.string   "cp_total_number_of_test_cards"
    t.string   "cp_total_num_of_cards"
    t.integer  "cp_iteration_tree___internal_qa_defect_card_id"
    t.string   "cp_points_hangover"
    t.string   "cp_points_attempted"
    t.string   "cp_points_completed_1"
    t.string   "cp_iteration_number"
    t.string   "cp_integrated_testing"
    t.string   "cp_translations_needed"
    t.string   "cp_actual_dev_estimate"
    t.integer  "cp_qa_tasked_by_user_id"
    t.string   "cp_test_pair"
    t.string   "cp_automation_actual"
    t.string   "cp_automation_estimate"
    t.string   "cp_qa_actual"
    t.string   "cp_number_of_total_cards"
    t.integer  "cp_iqd_card_id"
    t.date     "cp_release_date"
    t.string   "cp_rollback"
    t.string   "cp_qa_integration"
    t.string   "cp_5"
    t.string   "cp_defect_introduced"
    t.string   "cp_dev_resources"
    t.string   "cp_qa_resources"
    t.string   "cp_total_deployment_resources"
    t.string   "cp_automated_testing_duration"
    t.string   "cp_deployment_duration"
    t.string   "cp_manual_testing_duration"
    t.string   "cp_pre_deployment_duration"
    t.string   "cp_code_deployment_duration"
    t.string   "cp_mobile_impact"
    t.integer  "cp_iteration_tree___test_card_id"
    t.boolean  "redcloth"
    t.string   "cp_dependent_cards_"
    t.string   "cp_committed_points_complete"
    t.string   "cp_1"
    t.string   "cp_content_"
    t.date     "cp_deployment_date"
    t.string   "cp_deployment"
    t.string   "cp_test"
    t.string   "cp_codebase_domain"
    t.string   "cp_dev_estimate_planning"
    t.string   "cp_iteration_tree___internal_qa_defect"
    t.string   "cp_total_dev_points_completed"
    t.string   "cp_total_number_of_cards"
    t.string   "cp_blocked"
    t.string   "cp_comments"
    t.string   "cp_dependent_on"
    t.string   "cp_dev_tasked_by_1"
    t.string   "cp_feature_file_tester"
    t.string   "cp_rollback_"
  end

  add_index "ove_2_cards", ["number"], name: "index_ove_2_cards_on_number", unique: true, using: :btree

end
